### PR TITLE
feat: Add support for Requester Pays option on the Athena workgroup

### PR DESCRIPTION
**Pull request by chadinwork**
## what

- Add support for Requester Pays option on the Athena workgroup
- Update to `README.md` code from `make readme`

## why

- We have a business case for Requester Pays option on the Athena workgroup

## references

- https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-athena-supports-querying-data-from-amazon-s3/
- https://registry.terraform.io/providers/hashicorp/aws/5.72.1/docs/resources/athena_workgroup

### CODE REVIEW

**Comment by gberenice** [comment]
@chadinwork I know that it's not related to your work for this module, but could I ask you to resolve failing checks so we can proceed with merging this PR?

These inputs in [./examples/complete/variables.tf](https://github.com/cloudposse/terraform-aws-athena/blob/781d80e4a27bd29591aca26c0dd6ba6b332b8e2a/examples/complete/variables.tf) are missing descriptions:
```

Test: check if terraform inputs have descriptions
File: input-descriptions.bats
---------------------------------
data_catalogs is missing a description
databases is missing a description
named_queries is missing a description
region is missing a description
---------------------------------
```

Could you update this please? 🙏

**Comment by chadinwork** [comment]
@gberenice Sure. Here you go!

**Review by gberenice — APPROVED** [review]
LGTM, thanks for your contribution @chadinwork!

**Pull request merged**
